"""
tests/test_null_strategy.py — INFRA-005
========================================
End-to-end tests for NullStrategy through the full harness.

Parts covered:
  C1 — Accuracy mode (DSA leave-one-out, shortlist recall spot-check)
  C2 — Sweep mode (automated small matrix; 3-node and 5-node sizes)
  C3 — Resume / deduplication; --max-llm-calls semantics
  C4 — --names-file validation (plain list and meta-object formats)
  B4 — NullStrategy conformance subclass (uses_embeddings=False)

Placeholder names for sweep tests:
  Generated by make_placeholder_names() below. These are NOT thesis artifacts —
  they are clearly labelled placeholder names for test harness exercising only.
  They follow snake_case and do not overlap with any corpus node.

  Format: placeholder_concept_NNNNN (e.g. placeholder_concept_00001)
  This satisfies: ^[a-z][a-z0-9]*(_[a-z0-9]+)*$
  No corpus node has this prefix (verified: all corpus nodes are real concept names).
"""

from __future__ import annotations

import json
import os
import re
import sys
import tempfile
import time
from pathlib import Path
from typing import Any, Callable, Optional

import pytest

# Ensure src is importable
REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from graph_insertion.embedding import FakeEmbedder, MeteredEmbedder
from graph_insertion.graph_representation import ConceptGraph
from graph_insertion.harness import (
    HarnessConfig,
    SyntheticNameSource,
    run_accuracy_experiment,
    run_experiment,
    run_sweep_experiment,
)
from graph_insertion.llm import FakeLLMClient, MeteredLLMClient
from graph_insertion.loader import load_corpus, discover_corpora
from graph_insertion.decision import PROMPT_VERSION, PairwiseDecisionStep
from graph_insertion.strategies.null import NullStrategy
from graph_insertion.strategy import (
    DecisionOutcome,
    DecisionStep,
    Shortlist,
    insert_node,
)

# Import conformance suite
from tests.test_strategy_interface import StrategyConformanceSuite


# ===========================================================================
# Helpers
# ===========================================================================

_SNAKE_CASE_RE = re.compile(r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$')


def make_placeholder_names(n: int, offset: int = 0) -> list[str]:
    """Generate n unique placeholder concept names for test use only.

    NOT thesis artifacts — clearly labelled as placeholder_concept_NNNNN.
    These do not collide with any gold corpus nodes.
    """
    return [f"placeholder_concept_{i + offset:05d}" for i in range(n)]


def make_fake_decision_step() -> DecisionStep:
    """Return a fake offline decision step that produces no edges and zero latency."""
    client = MeteredLLMClient(FakeLLMClient())
    return PairwiseDecisionStep(client)


def make_fake_embedder() -> FakeEmbedder:
    return FakeEmbedder(dim=16, seed=42)


# ===========================================================================
# B4 — NullStrategy Conformance Subclass
# ===========================================================================

class TestNullStrategyConformance(StrategyConformanceSuite):
    """NullStrategy must pass all non-embedding conformance tests."""

    uses_embeddings: bool = False

    @pytest.fixture
    def strategy_factory(self):
        def _factory(graph: ConceptGraph, embedder) -> NullStrategy:
            strat = NullStrategy(seed=42, k=2)
            strat.setup(graph, embedder)
            return strat
        return _factory


# ===========================================================================
# NullStrategy Unit Tests
# ===========================================================================

class TestNullStrategyUnit:
    @pytest.fixture
    def small_graph(self) -> ConceptGraph:
        g = ConceptGraph(domain_context="data structures")
        for name in ["alpha", "beta", "gamma", "delta"]:
            g.add_node(name)
        return g

    def test_shortlist_size_k1(self, small_graph):
        strat = NullStrategy(seed=42, k=1)
        strat.setup(small_graph, FakeEmbedder())
        sl = strat.shortlist("new_concept")
        assert len(sl.candidates) == 1
        assert "new_concept" not in sl.candidates
        assert sl.candidates[0] in small_graph.nodes()

    def test_shortlist_size_k3_limited_by_n(self, small_graph):
        """If k > n existing (excl. new), return all existing."""
        strat = NullStrategy(seed=42, k=10)
        strat.setup(small_graph, FakeEmbedder())
        sl = strat.shortlist("new_concept")
        assert len(sl.candidates) == 4  # 4 existing nodes
        assert "new_concept" not in sl.candidates

    def test_shortlist_empty_graph(self):
        g = ConceptGraph()
        strat = NullStrategy(seed=42, k=1)
        strat.setup(g, FakeEmbedder())
        sl = strat.shortlist("x")
        assert sl.candidates == ()

    def test_shortlist_excludes_new_name(self, small_graph):
        strat = NullStrategy(seed=42, k=10)
        strat.setup(small_graph, FakeEmbedder())
        sl = strat.shortlist("alpha")  # alpha is already in graph
        assert "alpha" not in sl.candidates

    def test_determinism_same_seed(self, small_graph):
        """Same seed → same shortlist for same graph."""
        strat1 = NullStrategy(seed=99, k=2)
        strat1.setup(small_graph, FakeEmbedder())
        strat2 = NullStrategy(seed=99, k=2)
        strat2.setup(small_graph, FakeEmbedder())
        sl1 = strat1.shortlist("new_concept")
        sl2 = strat2.shortlist("new_concept")
        assert sl1.candidates == sl2.candidates

    def test_different_seed_may_differ(self, small_graph):
        """Different seeds should generally produce different results (with enough candidates)."""
        strat1 = NullStrategy(seed=1, k=2)
        strat1.setup(small_graph, FakeEmbedder())
        strat2 = NullStrategy(seed=2, k=2)
        strat2.setup(small_graph, FakeEmbedder())
        sl1 = strat1.shortlist("new_concept")
        sl2 = strat2.shortlist("new_concept")
        # With seed=1 vs seed=2 and 4 candidates, results may differ
        # We just ensure both are valid
        for c in sl1.candidates:
            assert c in small_graph.nodes()
        for c in sl2.candidates:
            assert c in small_graph.nodes()

    def test_config(self):
        strat = NullStrategy(seed=7, k=3)
        cfg = strat.config()
        assert cfg == {"seed": 7, "k": 3}

    def test_diagnostics(self, small_graph):
        strat = NullStrategy(seed=42, k=1)
        strat.setup(small_graph, FakeEmbedder())
        diag = strat.diagnostics()
        assert diag["k"] == 1
        assert diag["candidate_count"] == 4

    def test_on_inserted_noop(self, small_graph):
        strat = NullStrategy(seed=42, k=1)
        strat.setup(small_graph, FakeEmbedder())
        # Should not raise
        strat.on_inserted("new_concept", ())
        strat.on_inserted("other", (("new_concept", "other"),))

    def test_embedder_not_stored(self, small_graph):
        """NullStrategy must NOT store the embedder."""
        strat = NullStrategy(seed=42, k=1)
        fake_emb = FakeEmbedder()
        strat.setup(small_graph, fake_emb)
        assert strat._embedder is None

    def test_scores_all_zero(self, small_graph):
        strat = NullStrategy(seed=42, k=2)
        strat.setup(small_graph, FakeEmbedder())
        sl = strat.shortlist("new_concept")
        assert all(s == 0.0 for s in sl.scores)


# ===========================================================================
# C1 — Accuracy Mode: DSA Leave-One-Out
# ===========================================================================

class TestNullStrategyAccuracyMode:
    """C1 — Accuracy mode through the full harness on DSA (offline FakeLLM)."""

    @pytest.fixture
    def dsa_corpus(self):
        return load_corpus("DSA")

    def test_dsa_loo_basic_metrics(self, dsa_corpus, tmp_path):
        """All 29 DSA nodes: n_before==28, shortlist_size==1, llm_calls==1, embedding_calls==0."""
        config = HarnessConfig(
            mode="accuracy",
            run_id="test_null_accuracy_dsa",
            output_dir=tmp_path / "accuracy_dsa",
            seed=42,
            confirm=True,
        )
        decision_step = make_fake_decision_step()
        strategy_factory = lambda: NullStrategy(seed=42, k=1)
        embedder_factory = make_fake_embedder

        result = run_accuracy_experiment(
            config=config,
            strategy_factory=strategy_factory,
            decision_step=decision_step,
            embedder_factory=embedder_factory,
            corpora={"DSA_gold_standard_MEKG": dsa_corpus},
        )
        assert result["status"] == "completed"

        # Load raw.jsonl and verify per-record metrics
        raw_path = tmp_path / "accuracy_dsa" / "raw.jsonl"
        assert raw_path.exists()
        records = [json.loads(line) for line in raw_path.read_text().strip().splitlines() if line.strip()]
        success_recs = [r for r in records if r.get("status") == "success"]

        assert len(success_recs) == 29, f"Expected 29 successful records, got {len(success_recs)}"

        for rec in success_recs:
            m = rec["metrics"]
            assert m["n_before"] == 28, f"n_before={m['n_before']} for node {rec['node']}"
            assert m["shortlist_size"] == 1, f"shortlist_size={m['shortlist_size']}"
            assert m["llm_calls"] == 1, f"llm_calls={m['llm_calls']}"
            assert m["embedding_calls"] == 0, f"embedding_calls={m['embedding_calls']}"
            assert m["embed_s"] == 0.0
            assert m["embedding_calls_in_update"] == 0

    def test_shortlist_recall_spot_check(self, dsa_corpus, tmp_path):
        """C1 spot-check: independently compute expected shortlisted candidate for 3 specific nodes.

        NullStrategy(seed=42, k=1) draws from sorted(graph.nodes()) using random.Random(42).
        We verify shortlist_recall matches expected value (1 if gold edge exists, else 0).
        """
        import random

        gold_graph = dsa_corpus.graph
        all_nodes = sorted(gold_graph.nodes())
        # Pick 3 held-out nodes deterministically
        test_nodes = all_nodes[:3]

        config = HarnessConfig(
            mode="accuracy",
            run_id="test_null_spot",
            output_dir=tmp_path / "spot_check",
            seed=42,
            confirm=True,
        )
        decision_step = make_fake_decision_step()
        strategy_factory = lambda: NullStrategy(seed=42, k=1)
        embedder_factory = make_fake_embedder

        result = run_accuracy_experiment(
            config=config,
            strategy_factory=strategy_factory,
            decision_step=decision_step,
            embedder_factory=embedder_factory,
            corpora={"DSA_gold_standard_MEKG": dsa_corpus},
        )

        raw_path = tmp_path / "spot_check" / "raw.jsonl"
        recs_by_node = {
            r["node"]: r
            for r in (json.loads(l) for l in raw_path.read_text().strip().splitlines() if l.strip())
            if r.get("status") == "success"
        }

        for held_out in test_nodes:
            # Independently compute expected shortlisted node
            existing = [n for n in sorted(gold_graph.nodes()) if n != held_out]
            rng = random.Random(42)
            expected_candidate = rng.sample(existing, 1)[0]

            rec = recs_by_node[held_out]
            # Verify shortlist size in rec
            assert rec["metrics"]["shortlist_size"] == 1

            # shortlist_recall: fraction of gold neighbours in shortlist (k=1 so at most 1 hit)
            gold_neighbors = set(gold_graph.prerequisites_of(held_out)) | set(gold_graph.dependents_of(held_out))
            if len(gold_neighbors) > 0:
                expected_shortlist_recall = 1.0 / len(gold_neighbors) if expected_candidate in gold_neighbors else 0.0
            else:
                expected_shortlist_recall = None

            actual_shortlist_recall = rec["score"].get("shortlist_recall")
            if actual_shortlist_recall is not None and expected_shortlist_recall is not None:
                assert abs(actual_shortlist_recall - expected_shortlist_recall) < 1e-9, (
                    f"Node {held_out}: expected shortlist_recall={expected_shortlist_recall}, "
                    f"got {actual_shortlist_recall} (candidate={expected_candidate}, n_neighbors={len(gold_neighbors)})"
                )
            elif expected_shortlist_recall is None:
                assert actual_shortlist_recall is None

    def test_shortlist_recall_in_valid_range(self, dsa_corpus, tmp_path):
        """shortlist_recall is always in [0, 1] across all 29 DSA nodes."""
        config = HarnessConfig(
            mode="accuracy",
            run_id="test_null_recall_range",
            output_dir=tmp_path / "recall_range",
            seed=42,
            confirm=True,
        )
        result = run_accuracy_experiment(
            config=config,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            corpora={"DSA_gold_standard_MEKG": dsa_corpus},
        )
        raw_path = tmp_path / "recall_range" / "raw.jsonl"
        for line in raw_path.read_text().strip().splitlines():
            rec = json.loads(line)
            if rec.get("status") == "success":
                sr = rec.get("score", {}).get("shortlist_recall")
                if sr is not None:
                    assert 0.0 <= sr <= 1.0, f"shortlist_recall={sr} out of range for node {rec['node']}"


# ===========================================================================
# C2 — Sweep Mode Tests (automated, small sizes)
# ===========================================================================

class TestNullStrategySweepMode:
    """C2 — Sweep mode through the full harness with placeholder names."""

    def _make_name_source(self, n: int, offset: int = 0) -> SyntheticNameSource:
        names = make_placeholder_names(n, offset=offset)
        return SyntheticNameSource(names=names, domain_context="computer science")

    def test_sweep_no_edges_small(self, tmp_path):
        """Sizes [3, 5], 2 trials: n_before==size, unique keys, timestamp present."""
        name_source = self._make_name_source(200)
        config = HarnessConfig(
            mode="sweep",
            run_id="test_null_sweep_no_edges",
            output_dir=tmp_path / "sweep_no_edges",
            seed=42,
            sweep_sizes=(3, 5),
            sweep_trials_per_size=2,
            confirm=True,
        )
        result = run_sweep_experiment(
            config=config,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )
        assert result["status"] == "completed"

        raw_path = tmp_path / "sweep_no_edges" / "raw.jsonl"
        records = [json.loads(l) for l in raw_path.read_text().strip().splitlines() if l.strip()]
        assert len(records) == 4  # 2 sizes × 2 trials

        keys = [r["key"] for r in records]
        assert len(set(keys)) == len(keys), "Duplicate trial keys detected"

        for rec in records:
            assert "timestamp" in rec, "Missing timestamp field"
            assert rec.get("status") == "success"
            m = rec["metrics"]
            expected_size = rec["size"]
            assert m["n_before"] == expected_size, f"n_before={m['n_before']} != size={expected_size}"
            assert m["shortlist_size"] == 1
            assert m["llm_calls"] == 1
            assert m["embedding_calls"] == 0

    def test_sweep_with_edges_small(self, tmp_path):
        """Sizes [3], 1 trial with a decision step that always returns one edge."""

        class AlwaysEdgeDecisionStep:
            PROMPT_VERSION = "v2"

            def decide(self, new_name, candidates, domain_context=None):
                if candidates:
                    c = candidates[0]
                    edge = (c, new_name) if c < new_name else (new_name, c)
                    return DecisionOutcome(edges=(edge,), llm_calls=len(candidates), llm_seconds=0.0)
                return DecisionOutcome(edges=(), llm_calls=0, llm_seconds=0.0)

        name_source = self._make_name_source(50)
        config = HarnessConfig(
            mode="sweep",
            run_id="test_null_sweep_edges",
            output_dir=tmp_path / "sweep_edges",
            seed=42,
            sweep_sizes=(3,),
            sweep_trials_per_size=1,
            confirm=True,
        )
        result = run_sweep_experiment(
            config=config,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=AlwaysEdgeDecisionStep(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )
        assert result["status"] == "completed"

        raw_path = tmp_path / "sweep_edges" / "raw.jsonl"
        rec = json.loads(raw_path.read_text().strip())
        assert rec["status"] == "success"
        assert rec["metrics"]["llm_calls"] == 1

    def test_sweep_per_trial_seeds_derived_from_size(self, tmp_path):
        """Trial seed must be seed + n*1000 + trial_idx (as in harness.py)."""
        import random as _random
        name_source = self._make_name_source(200)
        config = HarnessConfig(
            mode="sweep",
            run_id="test_null_sweep_seeds",
            output_dir=tmp_path / "sweep_seeds",
            seed=42,
            sweep_sizes=(5,),
            sweep_trials_per_size=3,
            confirm=True,
        )
        run_sweep_experiment(
            config=config,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )
        raw_path = tmp_path / "sweep_seeds" / "raw.jsonl"
        records = [json.loads(l) for l in raw_path.read_text().strip().splitlines() if l.strip()]
        # Verify unique trial keys
        keys = [r["key"] for r in records]
        assert len(set(keys)) == 3
        # Verify n_before is always 5
        for rec in records:
            assert rec["metrics"]["n_before"] == 5


# ===========================================================================
# C3 — Resume / Deduplication and --max-llm-calls
# ===========================================================================

class TestNullStrategyResume:
    """C3 — Resume/dedupe: interrupt midway, rerun, check no duplicate keys."""

    def _make_name_source(self, n: int) -> SyntheticNameSource:
        return SyntheticNameSource(
            names=make_placeholder_names(n),
            domain_context="computer science",
        )

    def test_resume_no_duplicates(self, tmp_path):
        """Run 3 trials, abort after 1, resume, assert exactly 3 unique keys."""
        name_source = self._make_name_source(200)
        out = tmp_path / "resume_run"
        run_id = "test_null_resume"

        # First partial run: max_llm_calls=1 to stop after first trial
        config1 = HarnessConfig(
            mode="sweep",
            run_id=run_id,
            output_dir=out,
            seed=42,
            sweep_sizes=(3,),
            sweep_trials_per_size=3,
            max_llm_calls=1,
            confirm=True,
        )
        run_sweep_experiment(
            config=config1,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )

        # Read partial results
        raw_path = out / "raw.jsonl"
        partial_lines = [l for l in raw_path.read_text().strip().splitlines() if l.strip()]
        assert len(partial_lines) >= 1, "Expected at least 1 record after partial run"

        # Second run: resume=True, no max_llm_calls limit
        config2 = HarnessConfig(
            mode="sweep",
            run_id=run_id,
            output_dir=out,
            seed=42,
            sweep_sizes=(3,),
            sweep_trials_per_size=3,
            confirm=True,
            resume=True,
        )
        run_sweep_experiment(
            config=config2,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )

        # Final state: exactly 3 records, no duplicate keys
        final_lines = [l for l in raw_path.read_text().strip().splitlines() if l.strip()]
        records = [json.loads(l) for l in final_lines]
        keys = [r["key"] for r in records if r.get("status") == "success"]
        assert len(keys) == 3, f"Expected 3 successful records, got {len(keys)}"
        assert len(set(keys)) == len(keys), f"Duplicate keys found: {keys}"

    def test_max_llm_calls_is_process_local_not_cumulative(self, tmp_path):
        """--max-llm-calls counts calls in the current process only, not resumed records.

        Per harness.py: max_llm_calls cap is evaluated via cumulative_llm_calls, which
        starts at 0 at process start and does NOT include records from prior runs.
        This means a resume with max_llm_calls=N can make N more calls even if the
        prior run already made many calls.
        """
        name_source = self._make_name_source(200)
        out = tmp_path / "max_calls_resume"
        run_id = "test_max_calls"

        # Run 2 trials
        config1 = HarnessConfig(
            mode="sweep",
            run_id=run_id,
            output_dir=out,
            seed=42,
            sweep_sizes=(3,),
            sweep_trials_per_size=5,
            max_llm_calls=2,
            confirm=True,
        )
        run_sweep_experiment(
            config=config1,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )
        raw_path = out / "raw.jsonl"
        after_first = sum(1 for l in raw_path.read_text().strip().splitlines() if l.strip())

        # Resume with max_llm_calls=2: should allow 2 MORE calls (not affected by prior 2)
        config2 = HarnessConfig(
            mode="sweep",
            run_id=run_id,
            output_dir=out,
            seed=42,
            sweep_sizes=(3,),
            sweep_trials_per_size=5,
            max_llm_calls=2,
            confirm=True,
            resume=True,
        )
        run_sweep_experiment(
            config=config2,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )
        after_second = sum(1 for l in raw_path.read_text().strip().splitlines() if l.strip())
        # After resume with max_llm_calls=2, at least 1 more record should be added
        assert after_second >= after_first, "Resume should add records, not remove them"
        assert after_second <= 5, "Total cannot exceed sweep_trials_per_size=5"


# ===========================================================================
# C4 — --names-file Validation
# ===========================================================================

class TestNamesFileValidation:
    """C4 — Validate the names_file loading logic (plain list and meta-object)."""

    SNAKE_CASE_RE = re.compile(r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$')

    def _make_valid_names(self, n: int) -> list[str]:
        return make_placeholder_names(n)

    def _load_and_validate_names_file(
        self,
        path: Path,
        max_size: int,
    ) -> list[str]:
        """Replicate the names-file loading logic from run_experiment.py.

        Accepts either:
          - A plain JSON list: ["name1", "name2", ...]
          - An object: {"meta": {...}, "names": ["name1", ...]}

        Validates:
          - len(names) >= max_size + 1
          - No duplicates
          - All match snake_case pattern ^[a-z][a-z0-9]*(_[a-z0-9]+)*$
          - No overlap with any corpus node
        """
        data = json.loads(path.read_text())
        if isinstance(data, list):
            names = data
        elif isinstance(data, dict) and "names" in data:
            names = data["names"]
        else:
            raise ValueError(f"names-file must be a JSON array or an object with a 'names' key")

        if len(names) < max_size + 1:
            raise ValueError(
                f"names-file has {len(names)} names but max_size={max_size} requires at least {max_size + 1}"
            )
        if len(set(names)) != len(names):
            raise ValueError("names-file contains duplicate names")
        for name in names:
            if not self.SNAKE_CASE_RE.match(name):
                raise ValueError(f"Name {name!r} does not match snake_case pattern")

        # Check against corpus nodes
        all_corpora = discover_corpora()
        corpus_nodes: set[str] = set()
        for spec in all_corpora:
            try:
                lc = load_corpus(spec)
                corpus_nodes.update(lc.graph.nodes())
            except Exception:
                pass

        overlaps = set(names) & corpus_nodes
        if overlaps:
            raise ValueError(f"names-file names overlap with corpus nodes: {sorted(overlaps)[:5]}")

        return names

    def test_plain_list_format(self, tmp_path):
        names = self._make_valid_names(50)
        f = tmp_path / "names.json"
        f.write_text(json.dumps(names))
        loaded = self._load_and_validate_names_file(f, max_size=10)
        assert len(loaded) == 50
        assert loaded[0] == "placeholder_concept_00000"

    def test_meta_object_format(self, tmp_path):
        names = self._make_valid_names(50)
        f = tmp_path / "names.json"
        f.write_text(json.dumps({"meta": {"source": "generated", "seed": 42}, "names": names}))
        loaded = self._load_and_validate_names_file(f, max_size=10)
        assert len(loaded) == 50

    def test_insufficient_names_raises(self, tmp_path):
        names = self._make_valid_names(5)
        f = tmp_path / "names.json"
        f.write_text(json.dumps(names))
        with pytest.raises(ValueError, match="at least"):
            self._load_and_validate_names_file(f, max_size=10)

    def test_duplicates_raise(self, tmp_path):
        names = self._make_valid_names(20) + [self._make_valid_names(1)[0]]  # duplicate first name
        f = tmp_path / "names.json"
        f.write_text(json.dumps(names))
        with pytest.raises(ValueError, match="duplicate"):
            self._load_and_validate_names_file(f, max_size=5)

    def test_invalid_snake_case_raises(self, tmp_path):
        names = self._make_valid_names(20) + ["InvalidName", "has space", "123starts_with_digit"]
        f = tmp_path / "names.json"
        f.write_text(json.dumps(names))
        with pytest.raises(ValueError, match="snake_case"):
            self._load_and_validate_names_file(f, max_size=5)

    def test_overlap_with_corpus_raises(self, tmp_path):
        # Use actual DSA node names which will overlap
        dsa = load_corpus("DSA")
        corpus_names = sorted(dsa.graph.nodes())[:20]
        # Mix corpus names with placeholders to create overlap
        names = make_placeholder_names(10) + corpus_names
        f = tmp_path / "names.json"
        f.write_text(json.dumps(names))
        with pytest.raises(ValueError, match="overlap with corpus"):
            self._load_and_validate_names_file(f, max_size=5)

    def test_snake_case_pattern_valid_examples(self):
        """Verify the snake_case regex accepts valid examples."""
        valid = [
            "placeholder_concept_00001",
            "machine_learning",
            "l2",
            "concept",
            "abc123",
        ]
        for name in valid:
            assert self.SNAKE_CASE_RE.match(name), f"{name!r} should match snake_case"

    def test_snake_case_pattern_invalid_examples(self):
        """Verify the snake_case regex rejects invalid examples."""
        invalid = [
            "CamelCase",
            "_starts_with_underscore",
            "has space",
            "123starts_digit",
            "has--double-dash",
            "trailing_",
        ]
        for name in invalid:
            assert not self.SNAKE_CASE_RE.match(name), f"{name!r} should not match snake_case"


# ===========================================================================
# C2 full-matrix placeholder (to be replaced by actual run-by-hand results)
# ===========================================================================

class TestNullStrategySweepFullMatrix:
    """C2 — Reduced matrix test covering 3 sizes × 2 trials (automated proxy for the 6×10 matrix).

    The actual 6 sizes × 10 trials full D-35 matrix is run offline and results are
    reported in the task report (docs/reports/INFRA-005-claude-code-null-strategy-e2e.md).
    """

    def test_reduced_matrix_runs_clean(self, tmp_path):
        """3 sizes × 2 trials completes without errors and records are well-formed."""
        name_source = SyntheticNameSource(
            names=make_placeholder_names(2200),
            domain_context="computer science",
        )
        config = HarnessConfig(
            mode="sweep",
            run_id="test_null_matrix",
            output_dir=tmp_path / "matrix",
            seed=42,
            sweep_sizes=(50, 100, 200),
            sweep_trials_per_size=2,
            confirm=True,
        )
        result = run_sweep_experiment(
            config=config,
            strategy_factory=lambda: NullStrategy(seed=42, k=1),
            decision_step=make_fake_decision_step(),
            embedder_factory=make_fake_embedder,
            name_source=name_source,
        )
        assert result["status"] == "completed"

        raw_path = tmp_path / "matrix" / "raw.jsonl"
        records = [json.loads(l) for l in raw_path.read_text().strip().splitlines() if l.strip()]
        assert len(records) == 6  # 3 sizes × 2 trials

        for rec in records:
            assert rec["status"] == "success"
            assert "timestamp" in rec
            m = rec["metrics"]
            assert m["n_before"] == rec["size"]
            assert m["shortlist_size"] == 1
            assert m["llm_calls"] == 1
            assert m["embedding_calls"] == 0
            assert m["total_s"] >= 0.0
